lk-geimfari/awesomo

README.md

This commit corrects some grammar in the entry for Elizabeth.

Correct some grammar errors.

---

README.md

Simple static site generator for photoessays. :ghost:

Add Expose

---

languages/PYTHON.md

Really nice collection of projects, great job!
This PR fix the link for the pendulum project which wasn't in PYTHON.md.

Fix link for pendulum

---

languages/ERLANG.md

Add Riak KV/TS to erlang languages

Add Riak KV/TS to erlang

---

languages/C_C++.md
languages/GOLANG.md
languages/JAVASCRIPT.md

A fast, simple & powerful blog framework, powered by Node.js.

Add Hexo & Electron & Docker

---

languages/C_C++.md

It's the major cross-platform lib for GUIs with C++.

Add Qt to the C++ list

---

languages/JAVASCRIPT.md

Updating JAVASCRIPT.md :smile:

Add Clipboard.js, Reveal.js & Impress.js

---

languages/JAVASCRIPT.md

Yo, add this too. It ain't Mammoth's Shit :joy:

Add SweetAlert, Video.js, Ace, Dragula, Hyper, Docsify, WebTorrent & PhotoSwipe

---

languages/LUA.md

Added LuaPOSIX

---

languages/C_C++.md

If you want to do any creative coding that can span platforms and connect with many kinds of hardward, you need to check out [openFrameworks](http://openframeworks.cc/).
Here are just a few reasons why it's awesome:
* [main site's gallery](http://openframeworks.cc/gallery/)
* [top vimeo examples](https://vimeo.com/tag:openframeworks/sort:likes)

add openFrameworks

---

languages/JAVASCRIPT.md

A-Frame is a web framework for building virtual reality experiences.

Add A-Frame to JAVASCRIPT.md

---

languages/C_C++.md

Add Bitcoin

---

languages/ERLANG.md

Updated by the author of EMQ project

Update the introduction of emqttd project

---

languages/CSS.md

Changed btn.css to bttn.css

---

languages/COMMON_LISP.md
languages/EMACS_LISP.md

Separated Common Lisp and Emacs Lisp

---

README.md

Forgot to edit the readme, now fixed.

Fixed Common/Emacs Lisp sections

---

README.md
languages/TYPESCRIPT.md

I added TypeScript as discussed in #48

Added TypeScript

---

languages/C#.md

XUnit, Json.NET, RabbitMQ .NET client, Topshelf, MassTransit, Quartz Enterprise Scheduler .NET, SimpleInjector, Dapper.

Add C# open source projects

---

languages/GOLANG.md

Hello,
I'd like to ask you to remove iris project from the list. This is based on previous experience with the author https://github.com/avelino/awesome-go/pull/1135 and now a problem that I'd rather not disclose in public. I'd be happy to clarify if needed.
Thank you and sorry to drag you into this.

Remove iris

---

languages/GOLANG.md

Add go-callvis

---

languages/C#.md

[**Web Markup Minifier**](https://github.com/Taritsyn/WebMarkupMin) is .NET library that contains a set of markup minifiers. The objective of this project is to improve the performance of web applications by reducing the size of HTML, XHTML and XML code.

Added Web Markup Minifier to C#

---

languages/C++.md
languages/C.md

Adding more interesting C++/C projects: tox, VeraCrypt, OpenCV, i2pd, ArangoDB (#59)

Add C/C++ projects

---

languages/C#.md

Add Atata to C# language page

---

languages/GOLANG.md

Nanobox is another approach to what things like Docker Swarm and K8s is trying to accomplish. It tries to address the larger issue of infrastructure configuration/management rather than just one part of it (container orchestration)

Added Nanobox

---

languages/GOLANG.md

I think this is a nice addition to your list. Hopefully you agree. Check out the benchmarks as well if you're curious: https://github.com/vattle/sqlboiler#benchmarks -- Thanks.

Add SQLBoiler repo

---

languages/C#.md

Added 2 projects for C#

---

languages/PYTHON.md

Added my personal project Automatron to the Python list. It's not the most active in the world but I'm hoping to get it more exposure.
Let me know if the description is too long or anythign.

Added Automatron

---

languages/PYTHON.md

Hi,
I've added the Transcrypt Python to Javascript compiler under "Python".
Kind regards
Jacques de Hooge

Added the Transcrypt Python to Javascript compiler

---

languages/JAVASCRIPT.md

reason: ded
https://github.com/reactide/reactide/issues/122#issuecomment-320750396

Remove reactide

---

languages/PYTHON.md

**Adds [Evennia](https://github.com/evennia/evennia) to Awesomo's Python section**
Evennia is an actively-developed framework for creating and designing multiplayer text-based games - MOO, MUSH, MUD, and everything in-between.
Evennia is BSD-licensed, and instead of using a soft-code system, games are entirely programmed in Python on the filesystem. Evennia provides database abstraction through Django, as well as a built-in webserver, webclient, telnet server, and ssh server, and you can have a bare-bones game running in minutes.

Add Evennia, the Python MU* Framework, to Awesomo

---

languages/JAVASCRIPT.md

I'm adding a fairly active JavaScript test runner with beginner friendly issue.

Add AVA to JavaScript.md

---

languages/PYTHON.md

This adds a link explaining what a MUD is - to the Wikipedia article on them - and changes the logo to a higher quality version, but keeps the size small using an \<img\> tag.

Evennia Entry Changes

---

languages/PYTHON.md

Adds separator to Evennia entry - whoops!

Added Separator to Evennia Entry

---

languages/JAVASCRIPT.md

React based components catalog which provides you with markdown documentation and live examples.
https://github.com/OpusCapita/react-showroom-client

Add React Showroom

---

languages/PYTHON.md

Hypothesis is an awesome Python library, which means it should be on this list 😄 
I've added it just below Mimesis, because they have fairly similar goals and it made more sense to keep them together.

Add Hypothesis - powerful property based testing

---

languages/PYTHON.md

🎉 I think that's awesome enough to update the example here, too 😄

Update: Hypothesis can now find multiple bugs per test

---

languages/PYTHON.md

Click is a Python package for creating beautiful command line interfaces
in a composable way with as little code as necessary.  It's the "Command
Line Interface Creation Kit".

Added click in the list.

---

languages/PYTHON.md

Added [Monique Dashboards](https://github.com/monique-dashboards/monique) which is an innovative library for creating custom dashboards.

Add Monique Dashboards to PYTHON.md

---

languages/PYTHON.md

Reverts lk-geimfari/awesomo#98

Revert "Add Monique Dashboards to PYTHON.md"

---

languages/PYTHON.md

Reorder list alphabetically [Python].

---

languages/ELIXIR.md

Used the formatting from the Python list of projects, as requested in #101.

Order elixir.md alphabetically

---

languages/C.md

I used the formatting from the Python list of projects, as requested in #101.

Put C.md in alphabetical order

---

languages/R.md

`plyr` is a useful data manipulation library for the R statistical computing language.  `plyr` provides a means to query and analyze data that streamlines the plain R interfaces for `data.frame`s.

Add plyr to R.md

---

languages/C.md

Adds OptiKey to C# list

---

languages/PYTHON.md

BeeWare is a collection of projects that can be used to help develop, debug and launch Python software. Each tool follows the Unix philosophy of doing one thing well. Each tool can be used in isolation, or they can be chained together to provide a rich set of programming tools.

Added BeeWare project in PYTHON.md.

---

languages/JAVASCRIPT.md

Added a cool project I think belongs on this list. It's actively maintained and pretty useful if looking to use a markdown editor in the browser.

Added Dillinger Project

---

languages/CRYSTAL.md
languages/JAVA.md

Put both Crystal and Java in alphabetical order as requested in #101.

Crystal & Java in alphabetical order

---

languages/JAVASCRIPT.md

Using the Python example, as requested in #101

Order JAVASCRIPT.md alphabetically

---

languages/CSS.md

Order CSS.md alphabetically

---

languages/RUST.md

Matched the formatting from the Python list of projects as requested in #101.
Happy Hacktoberfest 🎃 !

Order RUST.md alphabetically

---

languages/PHP.md

Guzzle is a PHP library that allows you to make easy http requests to any kind of API.

Add Guzzle

---

languages/RUBY.md

Reading is so much easier when ordered alphabetically 
Similar to #101

[WIP] Order RUBy.md alphabetically

---

languages/C#.md

[WIP] Order C#.md alphabetically

---

languages/C#.md

Sorry, this one was missing the nav and a few other things.

Fix C#.md by removing duplications

---

languages/SWIFT.md

Order SWIFT.md alphabetically

---

languages/ERLANG.md

Order ERLANG.md alphabetically

---

languages/TYPESCRIPT.md

Order TypeScript.md alphabetically

---

languages/C++.md

Order C++.md alphabetically

---

languages/JAVASCRIPT.md

I'm not writing all these below points' description of what each means.
Take a look at [date-fns docs](https://date-fns.org/docs/) and you will understand.
- Modular
- Native Date
- Immutable & Pure
- TypeScript & Flow
- FP
- I18n
- Consistent
- Reliable
- Simple
- Fast
- Docs
- **More Coming!**

add date-fns a modern date lib

---

languages/PYTHON.md

It's an innovative deep probabilistic programming library maintained by Uber.

Added Pyro to the Python list.

---

languages/PYTHON.md

It's a huge open source deep learning library maintained by Facebook.

Added Pytorch to the Python list

---

README.md

Reverts lk-geimfari/awesomo#183

Revert "gramatical mistake"

---

languages/ERLANG.md

Chess representation written in Erlang using Bitboards, ready for use on game servers

Add Binbo to the Erlang list

---

languages/D.md

I copied KOTLIN.md based on D.md so I guess you find it good if the alphabet table is also included here

add alphabet table to D.md

---

languages/JAVASCRIPT.md

Changed image url for **sweetalert** under **JavaScript**.

Changed image url for sweetalert. Earlier image threw not found error

---

languages/JAVASCRIPT.md

Removed: 
Code Surfer,
Dillinger,
Iroh,
medium-editor
React-showroom
photoswipe

Updated JS list #180

---

languages/RUBY.md

This PR contains following changes:-
- Removed Celluloid as it has been archived.
- Added following new libraries:- 
+ aasm
+ cancancan
+ devise
+ factory_bot
+ jbuilder
+ kaminari

[#180] Update Ruby list

---

languages/ELIXIR.md

Added `cachex` - elixir library with a lot of functions focused on data caching.

Added cachex - elixir caching library

---

languages/ELIXIR.md

Updated Elixir Quantum repository URL.  
This already stored in file was marked as archived.

Updated Quantum GitHub repository URL

---

languages/JAVASCRIPT.md

This is a really cool framework for developers who are interested to learn or create music in the browser using JavaScript.

Add tone.js to the JavaScript list

---

languages/C++.md

Added Catch2, Dear Imgui and TensorFLow to the C++ list

Added Catch2, Dear Imgui and TensorFLow to the C++ list

---

languages/JAVA.md

Add Spring boot and SpringFox to Java list

---

languages/JAVASCRIPT.md

Svelte is a great project. Would like to add it to the list

add svelte to the js list

---

languages/RUST.md

Rustful is mammoth's s*** at this point. Its latest commit was on Jun 9, 2018.

Remove Rustful

---

languages/C#.md

ClosedXML is one of the best libraries I was using to manage Excel files (2007+). I was using few of those and I feel like OpenXML is doing good job. You can insert images, lock rows/columns, make charts, adjust size very easily. Definitely library you need to check.

Add ClosedXML

---

languages/PHP.md

add CakePHP

---

languages/RUST.md

Clippy is an actively developed collection of lints to catch common mistakes and improve Rust code.

Added Clippy

---

languages/RUST.md

Nu is a Rust shell under active development. It draws inspiration from projects like PowerShell, functional programming languages, and modern CLI tools. Rather than thinking of files and services as raw streams of text, Nu looks at each input as something with structure. For example, when you list the contents of a directory, what you get back is a table of rows, where each row represents an item in that directory. These values can be piped through a series of steps, in a series of commands called a 'pipeline'.

Added Nushell

---

languages/PYTHON.md

Universe was depricated and Voltron was not updated for more than one year. Hope this will help you :)

Change in Python List --> Deleted universe and voltron

---

languages/PHP.md

Add details of many frameworks like codeigniter, fulephp, yii, zend and many more...and s=also added reasons to use them and some image link to it.

Added Many Frameworks deatils and added img link in PHP.md file

---

awesomo.js

Added a new line 
console.log("I'm Fine")

Added to awesomo.js

---

languages/JAVASCRIPT.md

Added Hapijs Framework to readme Javascript

Added Hapijs to readme Javascript

---

languages/C#.md

Added Blazor to C#

---

languages/KOTLIN.md

I have added Corda to the kotlin list. Please merge it.

added corda to kotlin list

---

languages/JAVASCRIPT.md

I have added vue.js to the javascript list. Please merge it.

added vuejs to javascript list

---

languages/D.md

Correct from 'python'

---

languages/CSS.md

UIkit has been added to the CSS list. Please merge it.

Added UIkit to the CSS list

---

languages/JAVA.md
languages/PYTHON.md
languages/RUBY.md

Adding 3 awesome and active Open source project to the repository.

adding 3 new proyects to the repository

---

languages/RUST.md

I have added BoringTun to the Rust list. Please merge it

added boringtun to the rust list

---

languages/RUST.md

Reverts lk-geimfari/awesomo#251

Revert "added boringtun to the rust list"

---

languages/GOLANG.md

Add Helm to GOLANG.md

---

languages/ERLANG.md

Gave CouchDB and Disco Project a face. as in logos.

Added logos for CouchDB and Disco Project

---

languages/JAVASCRIPT.md

Add Serverless Framework to JAVASCRIPT.md

---

languages/SCALA.md

Added Apache Spark to the list.

Add Apache Spark to SCALA.md

---

languages/C#.md

Replaced archived FileSystem with Extensions

---

languages/JAVASCRIPT.md

[eDEX-UI](https://github.com/GitSquared/edex-ui) is an active open source project, with the benefit of looking extremely cool and actively trying to make open source more useful

Added eDEX-UI to Javascript

---

languages/HASKELL.md

Noticed a duplicate project listing, so I removed it.

Removing duplicate project.

---

languages/JAVASCRIPT.md

Updated JAVASCRIPT.md

---

languages/C#.md

A C# implementation of the WebSocket protocol client and server.

websocket-sharp

---

languages/KOTLIN.md

It is a useful framework as it allows developers to add security to an already existing solution and provides a really good replacement for simple password hashing.

Added Virgil PureKit to Kotlin

---

languages/JAVA.md

It is a useful framework as it allows developers to add security to an already existing solution and provides a really good replacement for simple password hashing.

Added Virgil PureKit to Java

---

languages/C#.md

is a tool and set of libraries which allows programmers to use C/C++ libraries with high-level programming languages (such as C#).

add CppSharp

---

languages/LUA.md

Moonscript is a pretty cool language written in itself and Lua designed to compile to Lua. Surprised this wasn't on the list before since we have leafo's Lapis, which is written partly in MoonScript.

Added moonscript

---

languages/C#.md

This repository contains algorithms and data structures implemented in C# for eductional purposes.

C-Sharp Algorithms

---

languages/KOTLIN.md

I don’t know why, but the github saw uncommitted changes

Add LibKTX to Kotlin

---

languages/KOTLIN.md

[Themis](https://github.com/cossacklabs/themis) is a popular open source cryptographic library available for 14 languages. Kotlin is one of supported languages, Themis has [docs and examples on Kotlin](https://docs.cossacklabs.com/themis/languages/kotlin/).

Add Themis for Kotlin

---

languages/JAVA.md

I added libraries that I used in Java project.
I thought that are really cool.

Added Java libraries 

---

languages/GOLANG.md
languages/PYTHON.md

It is a Simple and secure file/text sharing tool written in Golang.

Add Croc for Golang

---

languages/PYTHON.md

**RobotFramework** is one of well-known python and Java automation framework which provides capability for writing simple keywords driven test cases and implement easy automation fo enterprise applications.
here: https://robotframework.org/#introduction

Adding RobotFramework

---

languages/PHP.md

add framework list php

---

languages/PYTHON.md

With this engine we can create animations for math explanation in python

Added a Manim python animation engine

---

languages/JAVASCRIPT.md

Nice if compatible to hacktoberfest!

Adding VuePress Project in Javascript section

---

languages/JAVASCRIPT.md

BabylonJs is a powerful, beautiful, simple, and open game and rendering engine packed into a friendly JavaScript framework. It's also a real time 3D engine that displays graphics via HTML5. It has more than 12k stars on github.

Add Babylon.js in the Javascript section

---

languages/C++.md

While doing the other 2 PR I saw some broken image links so I fixed them and added the electron logo 😄
>I guess that there are many more broken images across other language files. I saw #245 which may fix the problem, but just for logos.

(C++) fixed 3 broken images + added electron image

---

languages/C++.md

Very popular and respected library (most notorious in Valve's Source engine). I used it in countless projects :)

Added SDL (C++ open-source cross-platform DirectMedia Layer)

---

languages/CLOJURE.md

Hi, I'd like to add `clojure-lsp` project which is a nice open-source project

Add clojure-lsp

---

languages/JAVA.md

i hope i am maintaining format of PR

vaadin framework is an important framework in java

---

languages/JAVASCRIPT.md

removed spaces & replaced - with —

consistant headers

---

languages/JAVASCRIPT.md

[**Insomnia**](https://github.com/Kong/insomnia) is an alternative to Postman and it's an awesome open source REST client for all desktop platforms. It has over 15k stars on GitHub, with a great community and active development.

Add Insomnia under JavaScript section

---

languages/SWIFT.md

[Themis](https://github.com/cossacklabs/themis) is a popular open source cryptographic library available for 14 languages. Swift is one of supported languages, Themis has [docs and examples on Swift](https://docs.cossacklabs.com/themis/languages/swift/).

Add Themis for Swift

---

languages/PYTHON.md

Hi!
I am biased on this topic (as I am the author of this project), but hopefully, Schemathesis can be added to the list as it is quite novel in some areas. In contrast with competitors, Schemathesis can:
- Generate data for GraphQL
- Work with partially invalid or incomplete schemas (can generate tests for >97% of all endpoints from the [API.guru catalog](https://github.com/APIs-guru/openapi-directory))
- Utilize property-based testing features like shrinking
- Supports WSGI/ASGI apps for in-process testing
- Execute tests concurrently
Cheers

Add Schemathesis

---

languages/GOLANG.md

the readme in their repo ( https://github.com/flynn/flynn )  says it's no longer maintained

removed Flynn from the golang list

---

languages/JAVASCRIPT.md

Added Leaflet to JavaScript projects. One of the best libraries for having a map in your web app and mobile apps.

Add Leaflet to JavaScript projects

---

languages/SHELL.md

Added new projects in BASH shell.
- neofetch
- nvm
Rearranged existing bash projects and added index.

Added projects for shell

---

languages/RUBY.md

Add ruby webcrawler to ruby projects.

Add spidr to ruby

---

languages/GOLANG.md

Add apache devlake to golang

---

languages/ELIXIR.md

VPN / remote access tool written in Elixir. Has decent docs (https://docs.firezone.dev/) and is actively maintained.

Add Firezone to Elixir projects

---

languages/R.md

I added a line for tidyverse in the file for the R programming language, it is a set of R packages that has grown in popularity very fast and I think today is the default set of tools necessary for any data science project.

Add tidyverse to R

---

languages/GOLANG.md

kube-green is an operator to reduce CO2 footprint of your clusters

add kube-green project

---

languages/LUA.md

Add Kong, an API Gateway in Lua section.

Add Kong API Gateway

---

languages/PYTHON.md

MoviePy is an awesome Python library that lets you edit videos through code just like you do it through some of the apps. It has some cool features like cut, concatenation, adding Gifs, add credits/title,  merge subtitles, add music, etc. I feel it is a very helpful library with a ton of cool features.

Added MoviePy in Python.md

---

languages/RUBY.md

Add 'awesome print' gem to ruby listing projects

Add - 'awesome print' gem to ruby projects

---

languages/C++.md

Adds Blender to the list of open source C++ projects.

add Blender to the C++ list

---

languages/JAVASCRIPT.md

Added a new framework for Nodejs.

Added Routing-Controllers Framework for Node.

---

languages/RUBY.md

Add Paper trail to Ruby

---

languages/TYPESCRIPT.md

Add storybook project to TypeScript section.

add storybook to typescript

---

languages/C++.md

It is definitely not a dead project, it is new and has room to grow. It offers a solution of the relatively new IoT paradigm called "mist computing". It is cross-platform, suitable for embedded and high-end systems.

Added AREG SDK to the C++ list.

---

languages/PHP.md

Also fixed an empty bullet point after Codeigniter section.

Add Fat-Free Framework to php projects
