lk-geimfari/awesomo

languages/JAVASCRIPT.md
Fixed the missing link to the mongotron repo in JAVASCRIPT.md
=> Fixed link to mongotron repo.

README.md
I have changed the `Golang` to `Go` in the README file to use the official name.
=> Change `Golang` to `Go`

README.md, languages/C#.md, languages/C++.md, languages/C.md
I looked through the C_C++.md file, went through the github repos of each project, and added each C & C++ project into their own file. This is in response to issue #42.
I also noticed the C-SHARP file didn't use the # symbol or have a heading in the file. I went ahead and added those so the files would be sorted alphabetically in the directory and C-SHARP wasn't the first file above C.
I made sure to update the README to include the new links.
=> Seperate C & C++ & rename C-SHARP to C# for consistency

languages/RUST.md
Given all other tools of this kind are slower and awesome [description](http://blog.burntsushi.net/ripgrep) why I see no reason why ripgrep should be left out of this list.
=> ripgrep section added

languages/SHELL.md
Simple change, corrected "an docker" to "a docker"
=> fixed grammatical error in SHELL.md

languages/LUA.md
Luacheck is a static analyzer and a linter for Lua. Luacheck detects various issues such as usage of undefined global variables, unused variables and values, accessing uninitialized variables, unreachable code and more. Most aspects of checking are configurable: there are options for defining custom project-related globals, for selecting set of standard globals (version of Lua standard library), for filtering warnings by type and name of related variable, etc. The options can be used on the command line, put into a config or directly into checked files as Lua comments.
Luacheck supports checking Lua files using syntax of Lua 5.1, Lua 5.2, Lua 5.3 and LuaJIT. Luacheck itself is written in Lua and runs on all of mentioned Lua versions.
=> Add LuaCheck to Lua.md

languages/EMACS_LISP.md, languages/HASKELL.md
alphabetic order added in haskell and emacs-lisp following python markdown file's style
=> alphabetic order added in haskell and emacs-lisp #101

languages/JAVASCRIPT.md
Nylas mail is no longer being maintained and instead original developer is maintaining this fork called Mailspring now.
=> Changed Nylas mail to Mailspring

languages/JAVASCRIPT.md
I have added a new image url for **Countly**, **Docsify.** Under **JavaScript**. Idk how this works @lk-geimfari, I pulled a request for the first image of Countly, but then I added another commit for Docsify. Will I need another PR?
=> Fixed image URL(s) for some items in JavaScript. Old images threw a 404.

languages/RUST.md
it's an awesome alternative to `cat` with syntax highlighting and
git integration.
=> Add `bat` to the Rust projects

languages/JAVASCRIPT.md
web3.js javascript API has been added to the javascript list.
web3.js is a javascript API that is extensively used by developers in making ethereum based blockchain applications. It helps applications to an ethereum node using HTTP or IPC connection.
=> Added web3.js

languages/PYTHON.md
Hey there, I wanted to add the Calibre E-Book manager to the list Open Source projects.
The Calibre Ebook Manager is, as far as I am aware, the largest open source E-book-manager out there. It is licensed under the GNU Public License version 3 and is in active development for over ten years now. 
Its written mostly in Python >2.7.9 (not python 3 compatible) and uses some C/C++ code for system interfacing. It also includes instructions on how to set up a development environment [here](https://manual.calibre-ebook.com/develop.html)
I hope you will consider adding the project to your list!
=> Added Calibre Project to Python.md

languages/RUST.md
Servo is a prototype web browser engine written in the Rust language. It is currently developed on 64-bit macOS, 64-bit Linux, 64-bit Windows, and Android.
=> Added Servo

languages/GOLANG.md
Fix url logo for Snap taken from their github page
=> Fix logo url for Snap

languages/JAVASCRIPT.md
Relevant to #180 
The last commit to https://github.com/zenorocha/clipboard.js was over a year ago
=> removed clipboard.js, as inactive

languages/PYTHON.md
Hi! I'm a developer of the [Catalyst framework](https://github.com/catalyst-team/catalyst) for Deep Leaning on PyTorch. I would like to add a link to your list. We actively support the project and release a new release every month.
The data scientists community likes Catalyst. It is actively used for competitions on Kaggle. PyTorch has also added us to [its ecosystem](https://pytorch.org/ecosystem/).
=> Added Catalyst framework

languages/HASKELL.md
=> Fix broken logo url for PostgREST

languages/HASKELL.md
Hello, I want to add gifcurry to the list.
Gifcurry is amazing tool for making gif. Besides gui, gifcurry is also available in cli. Here is reason, from  its repo, why gifcurry is awesome:
=> Add Gifcurry for Haskell

languages/C++.md
Since 2001, OGRE has grown to become one of the most popular open-source rendering engines. I used it in multiple occasions and it's quite nice :)
> I added the link to the main website but there is a whole [org ](https://github.com/OGRECave) in github with many repos (including the engine itself). I you want I could switch the link to this [one](https://github.com/OGRECave/ogre).
=> Added Ogre3D (C++ open-source rendering engine)

languages/C#.md
Added https://mudblazor.com an ambitious Material Design component framework for Blazor with an emphasis on ease of use and clear structure. It is perfect for .NET developers who want to rapidly build web applications without having to struggle with CSS and Javascript. MudBlazor, being written entirely in C#, empowers them to adapt, fix or extend the framework and the multitude of examples in the documentation makes learning MudBlazor very easy. 
Design goals:
- Clean and aesthetic graphic design based on Material Design
- Clear and easy to understand structure
- Good documentation with many examples and source snippets
- All components are written entirely in C#, no JavaScript allowed (except absolutely necessary)
- All CSS is encapsulated, users largely don't need it (but they can)
- No …
=> Add MudBlazor to C#

languages/C#.md
There is a small typo in languages/C#.md.
Should read `educational` rather than `eductional`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, eductional -> educational

languages/OCAML.md
Updating BuckleScript (OCaml) name because it's changed to ReScript.
[BuckleScript is rebranding](https://rescript-lang.org/blog/bucklescript-is-rebranding)
=> Update BuckleScript name

languages/TYPESCRIPT.md
Hello, I'd like to add my project to the typescript list
the project is an Express-like web framework that targets the latest version of Node.js and is compiled to both CommonJS and native ESM, so you can use ES modules in node with this framework, without extra setup required.
link to project: https://github.com/talentlessguy/tinyhttp
=> Add tinyhttp to the TypeScript list

languages/PYTHON.md
Fixed Broken Links which no longer work for images and GIFs in Beeware , asciinema , pandas , mimesis , pipenv , py.test and saleor sections.
Fix Pipenv is no longer experimental tool.
Add updated official github repo for maya and keras.
=> Fix Broken links and Update PYTHON.md

languages/JAVASCRIPT.md
The old link point to old docs that won’t be updated.
The new link points to the most recent docs.
=> Update link to React documentation

languages/CRYSTAL.md
This pull request adds [Marten](https://github.com/martenframework/marten) - a web framework - to the list of projects featured for the Crystal programming language.
=> Add Marten framework
